### ISSUE TITLE
Broken method 'from_service_account_file' in class 'TextToSpeechAsyncClient'

### ISSUE THREAD

**Issue by 0xfadeef** [googleapis/python-texttospeech#103]
#### Environment details

  - OS type and version: OS X `10.11.6`
  - Python version: `3.8.6`
  - pip version: `20.2.1`
  - `google-cloud-texttospeech` version: `2.2.0`

#### Steps to reproduce

  1. Call `TextToSpeechAsyncClient.from_service_account_file` method.
  2. Created object has type `TextToSpeechClient` (should be `TextToSpeechAsyncClient`).

#### Code example

```python
>>> from google.cloud.texttospeech import TextToSpeechAsyncClient
>>> client = TextToSpeechAsyncClient.from_service_account_file(...)
>>> type(client)
<class 'google.cloud.texttospeech_v1.services.text_to_speech.client.TextToSpeechClient'>
```

Project `googleapis/python-speech` had the same issue. See the patch here: https://github.com/googleapis/python-speech/commit/3bed0b43c75be649e29475240c7f486fc9cd63dc

**Comment by b-loved-dreamer** [comment]
Hi @0xfadeef — we're currently working on a fix for this issue.

**Comment by b-loved-dreamer** [comment]
Closing this issue. The relevant team has a fix that is underway or completed.
