### ISSUE TITLE
AttributeError: module 'google.cloud.texttospeech' has no attribute 'SynthesisInput'

### ISSUE THREAD

**Issue by KrisEdison** [googleapis/python-texttospeech#111]
Hi am using this code from the documentation:

`def synthesize_text(text):
    """Synthesizes speech from the input string of text."""
    from google.cloud import texttospeech

    client = texttospeech.TextToSpeechClient(credentials="D:/tts.json")

    input_text = texttospeech.SynthesisInput(text=text)

    # Note: the voice can also be specified by name.
    # Names of voices can be retrieved with client.list_voices().
    voice = texttospeech.VoiceSelectionParams(
        language_code="en-US",
        name="en-US-Standard-C",
        ssml_gender=texttospeech.SsmlVoiceGender.FEMALE,
    )

    audio_config = texttospeech.AudioConfig(
        audio_encoding=texttospeech.AudioEncoding.MP3
    )

    response = client.synthesize_speech(
        request={"input": text, "voice": voice, "audio_config": audio_config}
    )

    # The response's audio_content is binary.
    with open("output.mp3", "wb") as out:
        out.write(response.audio_content)
        print('Audio content written to file "output.mp3"')
`
I am getting the error **AttributeError: module 'google.cloud.texttospeech' has no attribute 'SynthesisInput'** when executing that function.

**Comment by munkhuushmgl** [comment]
Hey @KrisEdison 
which version of `google.cloud.texttospeech` are u using?
