### ISSUE TITLE
Calling client.synthesize_speech with 'await' doesn't work

### ISSUE THREAD

**Issue by JavRok** [googleapis/python-texttospeech#143]
Hi, according to the docs, `client.synthesize_speech` is an `async` function:

https://googleapis.dev/python/texttospeech/2.3.0/_modules/google/cloud/texttospeech_v1beta1/services/text_to_speech/async_client.html#TextToSpeechAsyncClient.synthesize_speech

But trying to run it with Python `asyncio` doesn't seem to work as expected. I get error:
`object SynthesizeSpeechResponse can't be used in 'await' expression`

I'm trying to run several jobs in parallel but I couldn't get it yet. Maybe my understanding of Python's async/await model is wrong? Hope this is not an stupid question 

#### Environment details

  - OS type and version:  Amazon Linux 2 (Lambda)
  - Python version: 3.8
  - pip version: 21.0.1
  - `google-cloud-texttospeech` version: 2.3.0
  - 
#### Code example

```python
...
transport = TextToSpeechGrpcTransport(channel=channel)
client = texttospeech_v1beta1.TextToSpeechClient(transport=transport)
request = texttospeech_v1beta1.SynthesizeSpeechRequest(...)
response = await client.synthesize_speech(request=request)

```

#### Stack trace
```
object SynthesizeSpeechResponse can't be used in 'await' expression
```

Thanks!

**Comment by munkhuushmgl** [comment]
Looks like you are not using Async Client in your snippet

```
async def synthesize_text(text):
    """Synthesizes speech from the input string of text."""
    from google.cloud import texttospeech_v1beta1 as texttospeech

    client = texttospeech.services.text_to_speech.async_client.TextToSpeechAsyncClient()

    input_text = texttospeech.SynthesisInput(text=text)
...... 
```

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided  feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Comment by JavRok** [comment]
Thanks for the help, I managed to run it in a lambda context and the performance boost is great !

One note is that it was not working even with the Async client, due to the custom gRPC transport (**TextToSpeechGrpcTransport**). There's an async version of it (_TextToSpeechGrpcAsyncIOTransport_), or the base transport also works. So in the end it looks like:
```
...
channel = TextToSpeechGrpcAsyncIOTransport.create_channel(
    options=[("grpc.max_receive_message_length", 30 * 1024 * 1024)]
)
transport = TextToSpeechGrpcAsyncIOTransport(channel=channel)
client = texttospeech_v1beta1.services.text_to_speech.TextToSpeechAsyncClient(transport=transport)
...
response = await client.synthesize_speech(request=request)
```

I must say the docs were not clear about this use-case, but thanks, it works !
