### ISSUE TITLE
protobuf pinning to < 4.0.0dev

### ISSUE THREAD

**Issue by bdraco** [googleapis/python-texttospeech#314]
Is it possible to remove or relax the `protobuf` pinning?

`google-cloud-texttospeech 2.12.0 has requirement protobuf<4.0.0dev,>=3.19.0, but you have protobuf 4.21.4.`

Thanks

**Comment by dandhlee** [comment]
Hey @bdraco, in the future we may remove this hard pin however at the moment to ensure that all client libraries can function properly, we've decided to pin it to below 4.0.0. I'll close it as not planned for now, but please re-open in the future if this is a recurring issue.
