### ISSUE TITLE
AttributeError: module 'google.cloud.texttospeech' has no attribute 'types'

### ISSUE THREAD

**Issue by kzkszk** [googleapis/python-texttospeech#61]
I use Google Cloud App Engine standard environment Python 3.7.

My app has worked well, but today it gives me error suddenly.

This is an error message.
```
File "/srv/main.py", line 84, in synthesize
    input_text = texttospeech.types.SynthesisInput(ssml=ssml)
AttributeError: module 'google.cloud.texttospeech' has no attribute 'types'
```

I searched the Internet and found the solution in this stackoverflow post.
https://stackoverflow.com/questions/62523362/i-cant-seem-to-make-the-google-cloud-texttospeech-to-work

I could solve this error by downgrading the library (I modified requirements.txt)
"google-cloud-texttospeech<2.0.0"

I have 3 App Engine apps which uses this python-texttospeech library in the same way, but only one app causes the problem.

Why does this error happen? Should I modify other apps' requirements.txt?

This is the part of my app's code.
```
@app.route("/synthesize", methods=['POST', 'GET'])
def synthesize():
    if request.method == "POST":
        if request.form['Radio'] == 'normal':
            ssml = '<speak><prosody rate="slow">' + request.form['text'] + '</prosody></speak>'
        else:
            ssml = '<speak>' + request.form['text'] + '</speak>'    
            
        accent = request.form['accent']
        voiceid = next((voice for voice in request.form.getlist('voiceId[]') if accent in voice), None)
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="credentials.json"
 
        client = texttospeech.TextToSpeechClient()
        input_text = texttospeech.types.SynthesisInput(ssml=ssml)
        voice = texttospeech.types.VoiceSelectionParams(
            language_code=accent,
            name=voiceid)

        audio_config = texttospeech.types.AudioConfig(
            audio_encoding=texttospeech.enums.AudioEncoding.MP3)

        response = client.synthesize_speech(input_text, voice, audio_config)

        with open('/tmp/output.mp3', 'wb') as out:
            out.write(response.audio_content)

        return send_file("/tmp/output.mp3",as_attachment=True)
    else:
        return render_template("synthesize.html")
```

**Comment by munkhuushmgl** [comment]
@kzkszk There has been a breaking change related to types and enums:
https://github.com/googleapis/python-texttospeech/blob/master/UPGRADING.md#enums-and-types

**Comment by kzkszk** [comment]
@munkhuushmgl  Thank you very much for your advice. I will follow this UPGRADING.md.

**Comment by kzkszk** [comment]
@munkhuushmgl I overcame my problem. I really appreciate your help.

**Comment by cmicek1** [comment]
I'm running version 1.0.1 on the cloud shell and I think I ran into a similar issue. I'm trying to go along with the demo file, but now I have
```
File "make_script.py", line 13, in synthesize_ssml
    input_text = texttospeech.SynthesisInput(ssml=ssml)
AttributeError: 'module' object has no attribute 'SynthesisInput'

```
Not sure what the fix for this is though, since type and enum have already been eliminated here.
