### ISSUE TITLE
`scripts/fixup_keywords.py` not available after library installation

### ISSUE THREAD

**Issue by riqiang-dp** [googleapis/python-texttospeech#62]
Might be a silly question but:

I'm trying to update to 2.1 from 1.0.1 but I haven't been able to access this script after installing the package. I couldn't find more documentation or troubleshooting for this utility and with my limited experience I haven't seen other packages provide scripts like this before. (the file is simply not added to $PATH). Am I missing some step?
(I could simply use the script from this repo but I wonder what to do to make it work the intended way).

...........

Yes: `scripts/fixup_keywords.py` is published with the library.

If you install the library it will be available on the command line. https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument

_Originally posted by @busunkim96 in https://github.com/googleapis/python-texttospeech/pull/30#discussion_r433498731_

**Comment by busunkim96** [comment]
Hi @riqiang-dp,

We added the script to `scripts` in `setup.py`. https://github.com/googleapis/python-texttospeech/blob/4f416475686dc0dfad6a3fc1f1835a48cbf8d8b9/setup.py#L101 setuptools *should* copy it to your $PATH. https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument

That said, if it's causing you trouble I'd recommend you just run the script from the repo (or wherever the library is installed locally).

**Comment by riqiang-dp** [comment]
Thanks for your quick reply! Somehow it was not copied but I just used the script from the repo.
