### ISSUE TITLE
Syntax in sample application is out of date

### ISSUE THREAD

**Issue by speaklanguages** [googleapis/python-texttospeech#87]
The syntax for synthesizing a sound clip in the following sample application is out of date:

https://github.com/googleapis/python-texttospeech/blob/master/samples/snippets/quickstart.py

```
    # Perform the text-to-speech request on the text input with the selected
    # voice parameters and audio file type
    response = client.synthesize_speech(
        input=synthesis_input, voice=voice, audio_config=audio_config
    )
```

Should be:

```
    # Perform the text-to-speech request on the text input with the selected
    # voice parameters and audio file type
    response = client.synthesize_speech(
        request={
            "input": synthesis_input,
            "voice": voice,
            "audio_config": audio_config
        }
    )
```

**Comment by munkhuushmgl** [comment]
@speaklanguages I will take a look.

**Comment by munkhuushmgl** [comment]
just checked `quickstart.py` and it is working fine. 
![image](https://user-images.githubusercontent.com/45373284/91778001-2c62ea80-eba6-11ea-9db9-6b855186856c.png)

what python version are you running it on?

**Comment by speaklanguages** [comment]
I'm using Python 3.7 with version 2.2.0 of the google-cloud-texttospeech library. I'm using the updated syntax I suggested and it's working fine. I was under the impression that that syntax was the latest one and was necessary, but having read the following page, it appears that both variants I quoted in my original post will work.

https://googleapis.dev/python/texttospeech/latest/UPGRADING.html

However, using the syntax I suggested would be more consistent with the latest syntax to list_voices:

voices = client.list_voices(request={"language_code": "no"})

So perhaps it would make sense to update the example code anyway. Sorry for the false alarm, but I had some other issues when trying to implement the code, which is why I thought the example code wasn't working. In any case, it's potentially confusing to have two different syntax options for the same function, so perhaps it would be better to choose one and enforce it.

**Comment by speaklanguages** [comment]
Note that the documentation for the latest version says this:

> In the 2.0.0 release, all methods have a single positional parameter request.

**Comment by munkhuushmgl** [comment]
@speaklanguages looks like both options are acceptable. However, I will refactor the samples accordingly sometime this week.

**Comment by munkhuushmgl** [comment]
Looks like it would much more work than I expected. Since both cases are acceptable, I will leave as it is. (it is not really causing any big. issue)

Feel free to reopen if you having issue with it
