### ISSUE TITLE
enableTimePointing not supported

### ISSUE THREAD

**Issue by timitimi** [googleapis/python-texttospeech#95]
Having a look at your code you have not implemented the passing of this parameter (enableTimePointing) for the v1Beta version of the API, therefore there is no way to get back the time positioning of the marks in the SSML. 

Is there any way to do this for example in the metadata parameter ? Already tried with no luck.

Thanks !

#### Environment details

  - OS type and version: MacOs
  - Python version: `python --version` 3
  - pip version: `pip --version` 20.3 
  - `google-cloud-texttospeech` version: `pip show google-cloud-texttospeech` 2.2.0

#### Steps to reproduce

  1. Instantiate a texttospeech_v1beta1.TextToSpeechClient()
  2. Try to pass the 'enableTimePointing' parameter on the client creation

#### Code example

```python
response = client.synthesize_speech(    
        input=input_text, voice=voice, audio_config=audio_config, enableTimePointing='SSML_MARK')
    )

**Comment by timitimi** [comment]
Finally got it working !
` #Create a SynthetizeSpeechRequest
    request = texttospeech_v1beta1.SynthesizeSpeechRequest(
        input=input_text,
        voice=voice,
        audio_config=audio_config,
        enable_time_pointing=[texttospeech_v1beta1.SynthesizeSpeechRequest.TimepointType.SSML_MARK]
    )

    response = client.synthesize_speech(    
        request=request
    )`

**Comment by munkhuushmgl** [comment]
Since you solved your issue, I am closing this issue.

Feel free to reopen if you still have some issue with API
